---
backend:
  name: git-gateway
  branch: main
media_folder: "/posts"
public_folder: "/posts" 
collections:
  - name: "post" 
    label: "Post"
    folder: "/src/posts"
    create: true 
    slug: "{{slug}}" 
    fields: 
      - label: "Date"
        name: "Date"
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - {label: "Body", name: "body", widget: "markdown"}